### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by blyscuit** [kothihaaung/nimble-survey-ios#14]
Hello Thiha 👋 , thank you for your effort on the code submission. I am Bliss, Senior Software Engineer at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by blyscuit** [comment]
I have completed the first round of reviews. Please provide your feedback on all open issues. The order of priority is by the number id of the issue, the lower the id, the higher priority.

**Comment by kothihaaung** [comment]
Hello Bliss, thank you very much for thorough reviews.
I will try to fix and reply the issues.

**Comment by kothihaaung** [comment]
@blyscuit this [PR](https://github.com/kothihaaung/nimble-survey-ios/issues/18) is the last one I worked for this project.
To be honest, the project become too much for a coding test and way passed the original requirement.
I have fixed some of impotent issues I think reasonable. Cheers 🙌.

**Comment by blyscuit** [comment]
@kothihaaung Thank you for the heads up. Feel free to work on this until Monday midday. Focusing on the areas that you are confident in.

**Comment by kothihaaung** [comment]
@blyscuit 
Got 2 more PR #40 and #41 .

**Comment by blyscuit** [comment]
Good afternoon Thiha,

Thank you for your timely updates! As of now, my review for this code challenge session has concluded, and thus no more submissions will be needed from your end. For the next step, you will hear from the Talent Acquisition team about the decision as soon as we complete the evaluation.
