### ISSUE TITLE
[Feature] Supporting multiple application environments

### ISSUE THREAD

**Issue by blyscuit** [kothihaaung/nimble-survey-ios#15]
## Issue

In a real world development we will use more than 1 environments. Current application supports only Production environment.

## Acceptance Criteria

- Add a new `dev` environment.
    - `dev` environment uses the same `client_id` and `client_secret` as `production` but should be in a new field for easy modification later.
    - `dev` environment should build using a different bundle id than `production`.
- Developer should be able to select the environment easily from the Xcode UI.

**Comment by kothihaaung** [comment]
@blyscuit sorry, it looks like Github automatically close the issue when linked branch is merged.

**Comment by blyscuit** [comment]
@kothihaaung After pulling this branch, I was not able to use `bundle exec pod install` to install the dependencies. Please help check.

**Comment by kothihaaung** [comment]
If cannot, you may try it on main branch as well. Just pod install.

**Comment by blyscuit** [comment]
@kothihaaung `pod install` does not work for me. Could you fix the bundle file so that it works correctly.

**Comment by kothihaaung** [comment]
Actually pod keys are already installed as binary in the project.
You should able to run without doing anything.

**Comment by kothihaaung** [comment]
I am not sure it is your computer’s ruby version issue.
It run no problem for me.
I used latest one.

**Comment by kothihaaung** [comment]
You may try download as zip from and run.

**Comment by kothihaaung** [comment]
Could you also check the README in main branch?
I updated the instructions to run with CocoaPods Keys.

**Comment by blyscuit** [comment]
@kothihaaung My ruby version is `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]`, however it should not impact the issue with cocoapods-keys. 

Another question on the environment set up. How should I proceed if I would like to use breakpoint on the `PROD` environment?

**Comment by kothihaaung** [comment]
Can you run the project now?

sorry I don’t get your question.
You can use break points normally.

**Comment by kothihaaung** [comment]
In latest main branch, there is baseurl inside Constant for dev and prod.
You may change the values of each env and check if you want to check environment.

**Comment by kothihaaung** [comment]
@blyscuit i think you need to install cocoa pods-key gem first.

**Comment by kothihaaung** [comment]
I missed this one in README. Will update it.

**Comment by blyscuit** [comment]
@kothihaaung Please check `Gemfile` to fix the issue with cocoapods-keys. This should be enough hint to fix the issue.

I am not able to use breakpoint on `PROD` environment.

**Comment by kothihaaung** [comment]
What do you mean you cannot do break points?

**Comment by kothihaaung** [comment]
Can you tell me in detail, what you are trying to do?

may be with image to help me understand.

**Comment by blyscuit** [comment]
@kothihaaung Does this breakpoint works for you? Also try after Clean and Build.
<img width="342" alt="Screenshot 2567-04-18 at 16 42 46" src="https://github.com/kothihaaung/nimble-survey-ios/assets/6356137/3a7c30b0-80ec-471d-b803-2de542bbe801">

**Comment by kothihaaung** [comment]
@blyscuit may be you can just print it out the env var inside the Constant.

**Comment by kothihaaung** [comment]
You want to check macro is working or not, right?

**Comment by kothihaaung** [comment]
@blyscuit I encounter break point issue on PROD as well. Will try to fix that.

**Comment by kothihaaung** [comment]
@blyscuit it cannot debug but it is actually working.
I tested like this. 
Added additional attribute to `Constant`.
```
var hello: String {
        switch env {
        case .dev:
            "Hello DEV"
        case .prod:
            "Hello PROD"
        }
    }
```
<img width="777" alt="Screenshot 2024-04-19 at 7 42 59" src="https://github.com/kothihaaung/nimble-survey-ios/assets/22878813/d88f6d25-8b78-464a-93e8-bc485aeb7fd1">
<img width="732" alt="Screenshot 2024-04-19 at 7 43 32" src="https://github.com/kothihaaung/nimble-survey-ios/assets/22878813/f24da2e6-2367-4e5f-bf91-d84d54f17391">
