### ISSUE TITLE
[Chore] Hide secrets from source code

### ISSUE THREAD

**Issue by blyscuit** [kothihaaung/nimble-survey-ios#17]
## Issue

Secret should not be pushed via git which can be misused by unauthorized person.

## Acceptance Criteria

- The application should be able to read secrets while it is not presented in the source code.
- Application should behave the same as before the change.

**Comment by kothihaaung** [comment]
@blyscuit this issue is fixed along with PR(https://github.com/kothihaaung/nimble-survey-ios/pull/35).
