### ISSUE TITLE
[Bug] When fetching load more, page number in page indicator does not update

### ISSUE THREAD

**Issue by blyscuit** [kothihaaung/nimble-survey-ios#21]
## Issue

When fetching load more, page number in page indicator is reset.

## Expected

Fetching load more should update the page indicator by appending the new result to the current data. Example: current page count = 3, user receives 3 new pages, page count = 6.

## **Step To Reproduce**

1. Log in.
2. Scroll through the survey list.
3. Observe the page number indicator.

https://github.com/kothihaaung/nimble-survey-ios/assets/6356137/01c56683-620b-417b-b371-6b3d47ca304c

**Comment by kothihaaung** [comment]
As per design, I though that it is intended to show current page size only.
Because if we append with already loaded pages, the indicator would not look good when new pages keep increasing the size.

e.g
●●●●●●●●●●●●●●●●●●●
