### ISSUE TITLE
[Question] SwiftUI Previews

### ISSUE THREAD

**Issue by blyscuit** [kothihaaung/nimble-survey-ios#28]
## Issue

What is your workflow with SwiftUI Previews?

What lead you to not include SwiftUI Previews in this project?

**Comment by kothihaaung** [comment]
- SwiftUI Previews are not practically working when UIs are getting complex.
- It also easily fail when build time is getting longer than a few seconds.
- Hopefully it will improve in future.
- For me, running with Simulator is faster than previews so far.

**Comment by blyscuit** [comment]
@kothihaaung If you were to use SwiftUI Preview on a view that has some dependencies, including view model that is triggers by `onAppear` and calls API, how would you design the Preview?

**Comment by kothihaaung** [comment]
@blyscuit 
We could use EnvironmentObject in this case for view model.
And mock data in view model
This would work but my Preview is keep crashing 😵.
```
#Preview {
    var viewModel = SurveyListViewModel()
    // mock data in view model
    viewModel.uiState = .normal
    
    return SurveyListView()
        .environmentObject(viewModel)
}
```
<img width="1292" alt="Screenshot 2024-04-18 at 10 02 21" src="https://github.com/kothihaaung/nimble-survey-ios/assets/22878813/a92ac007-68a6-4de5-8406-a2812d16eb7d">
