### ISSUE TITLE
[Question] Fastlane usage

### ISSUE THREAD

**Issue by blyscuit** [kothihaaung/nimble-survey-ios#29]
## Issue

What is fastlane used for in this project?

What fastlane’s role in your normal workflow? Provide code snippet for example if any.

**Comment by kothihaaung** [comment]
The main reason is because it was asked in the requirement.
<img width="271" alt="Screenshot 2024-04-18 at 0 58 02" src="https://github.com/kothihaaung/nimble-survey-ios/assets/22878813/43a1dfed-6ba9-42a2-a16d-d88da71fc474">

I usually use Fastlane to run some complex Xcode command line tool.
```
lane :tests do
  run_tests(workspace: "Example.xcworkspace",
            devices: ["iPhone 6s", "iPad Air"],
            scheme: "MyAppTests")
end
```

**Comment by blyscuit** [comment]
@kothihaaung What other usages Fastlane has in your workflow?

**Comment by kothihaaung** [comment]
@blyscuit 
I considered to use `xcov` to generate coverage report in the past. 
But no much usage of Fastlane recently.
```
xcov(
  workspace: "YourWorkspace.xcworkspace",
  scheme: "YourScheme",
  output_directory: "xcov_output"
)
```

**Comment by kothihaaung** [comment]
@blyscuit i use CICD but not with fastlane. 
With  Bitrise and Azure DevOps’s workflow item.

**Comment by kothihaaung** [comment]
@blyscuit 
Used Fastlane with GitHub action.
